### ISSUE TITLE
Protos updated : how to user protoc-gen-php

### ISSUE THREAD

**Issue by smourph** [jaspervdm/pogoprotos-php#15]
Hello,

Protos has been updated (see https://github.com/keyphact/pgoapi and https://github.com/AeonLucid/POGOProtos/tree/master). You may update your POGOProtos submodule.

In the meantime, I need to compile new files. What terminal command do you use to generate all compiled files at once ? When I use `protoc --php_out=. (...).proto` with each file one by on, I got import error with some of them.

**Comment by DrDelay** [comment]
I can only speak for the test-protobuf branch with the ["new" protobuf-plugin](https://github.com/protobuf-php). There you can simply call [compile.php](https://github.com/jaspervdm/pogoprotos-php/blob/test-protobuf/compile.php) and it does the job. I updated them in 94bafb3cd34e34b9cbe3dc1ef5c003bad1ca6699 just now if that helps you. Not tested yet, though.

The master branch is still on bramp's plugin, I don't get that to run, @jaspervdm would have to update that.

**Comment by smourph** [comment]
Ok, thanks !

**Comment by jaspervdm** [comment]
The current plan is to merge the test-protobuf into master. I can do it in a couple of days, but if you want DrDelay you can already do it

**Comment by DrDelay** [comment]
I may do that after some more testing. While I don't think that 94bafb3cd34e34b9cbe3dc1ef5c003bad1ca6699 introduced errors the ["AuthTicket stream thing"](https://github.com/jaspervdm/pogoprotos-php/issues/8#issuecomment-237035779) _should_ be looked at again.

As long as it is not tagged people requiring it via composer should not get conflicts. And due to being a BC-breaking change it would probably be get a new Major-version anyways, so "_caret_-users" are still good.
